version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - type:ci
      - skip-changelog
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - type:dependency
    groups:
      python-packages:
        patterns:
          - '*'
