name: Publish Python distribution to PyPI and make release on Github

on:
  workflow_call:

jobs:
  publish-to-pypi:
    name: Publish Python distribution to PyPI
    runs-on: ubuntu-22.04
    # if: github.repository == 'andy-takker/base-http-client'
    environment:
      name: pypi
      url: https://pypi.org/p/base-http-client/
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make develop-ci

      - name: Build distribution
        run: poetry build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.10
        with:
          verbose: true
          skip-existing: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/

  github-release:
    name: >-
      Sign the Python distribution with Sigstore
      and upload them to Github Release
    needs:
      - publish-to-pypi
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: python-package-dist
          path: dist/

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: ${{ github.ref_name }}
          body_path: changelog.md
          files: |
            dist/*

