name: Check project in all branches

on:
  workflow_call:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checking:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make develop

      - name: Run CI linters
        run: make lint-ci

  test:
    name: Run service tests with pytest
    runs-on: ubuntu-22.04
    container: python:3.10
    needs: checking
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make develop

      - name: Run pytest
        run: make test-ci

  notify:
    name: Notify successful CI
    needs: test
    runs-on: ubuntu-22.04
    env:
      GOTIFY_HOST: ${{ secrets.GOTIFY_HOST }}
      GOTIFY_APP_TOKEN: ${{ secrets.GOTIFY_APP_TOKEN }}
      GOTIFY_TITLE: Inclusive Dance Bot
      GOTIFY_MESSAGE: Checked repo ${{ github.REF_NAME }}
      GOTIFY_EVENT_NAME: ${{ github.EVENT_NAME  }}
      GOTIFY_REPOSITORY_URL: ${{ github.SERVER_URL }}/${{ github.REPOSITORY }}
      GOTIFY_ACTION_URL: ${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send notify
        run: python ./gotify.py
