name: Check project in all branches

on:
  workflow_call:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checking:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make develop-ci

      - name: Run CI linters
        run: make lint-ci

  test:
    name: Run service tests with pytest
    runs-on: ubuntu-22.04
    container: python:3.10
    needs: checking
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make develop-ci
