name: Publish Python distribution to PyPI and TestPyPI

on:
  workflow_call:

jobs:

  publish:
    name: Publish distribution
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
